#  --- 三个横杠可以区分多个配置环境信息
spring:
  profiles:
    active:         #激活如下的配置为开发环境
      -dev
---
server: 
  port: 7001
spring:
     profiles: dev    #开发环境
     application:
       name: springcloud-config-eureka-dev               #微服务名称
eureka: 
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称   eureka7001.com
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     # #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
#      defaultZone: http://eureka7001.com:7001/eureka   
---      
server: 
  port: 7001
spring:
     profiles: test    #开发环境
     application:
       name: springcloud-config-eureka-test               #微服务名称
eureka: 
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称   eureka7001.com
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     # #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
#      defaultZone: http://eureka7001.com:7001/eureka  

      
