#  --- 三个横杠可以区分多个配置环境信息
spring:
  profiles:
    active:         #激活如下的配置为开发环境
      -dev
---
server:
  port: 8001   
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: dev    #开发环境
   application:
    name: springcloud-config-xll-dev                           #配置服务器状态名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.10.146:3306/spring_cloud_01?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 #<---------------------------------Eureka 服务注册与发现的配置 start------------------------------------------>
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka     #单机版配置
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-config-xll    #设置eureka客户端status状态名称
    prefer-ip-address: true     #访问路径可以显示IP地址     
# 配置该状态url:的显示内容
info: 
  app.name: springcloud-config-xll-dev
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#<---------------------------------Eureka 服务注册与发现的配置 end------------------------------------------>

---
server:
  port: 8001   
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: test    #开发环境
   application:
    name: springcloud-config-xll-test                           #配置服务器状态名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.10.146:3306/spring_cloud_02?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 #<---------------------------------Eureka 服务注册与发现的配置 start------------------------------------------>
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka    #单机版配置
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-config-xll    #设置eureka客户端status状态名称
    prefer-ip-address: true     #访问路径可以显示IP地址     
# 配置该状态url:的显示内容
info: 
  app.name: springcloud-config-xll-test
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#<---------------------------------Eureka 服务注册与发现的配置 end------------------------------------------>
